issue-156: change plugin id to Grafana naming convention
VictoriaMetrics/victorialogs-datasource pull request #161
Opened 2024-12-16 17:15 UTC by dmitryk-dk

Renamed plugin id to Grafana naming convention. Updated README.md with related changes.

I checked how it works and how the Grafana checks new plugin name
<img width="1086" alt="Screenshot 2024-12-16 at 18 12 04" src="https://github.com/user-attachments/assets/b79585b8-c59c-4d55-bf52-c9586a06f42c" />

To run those changes it is required to update the defaults.ini  or grafana.ini file with the new plugin name in the `allow_loading_unsigned_plugins` field.
```
allow_loading_unsigned_plugins = victoriametrics-logs-datasource
```

Related issue: #156

2024-12-16 17:23 UTC, AndrewChubatiuk submitted a review, later dismissed

2024-12-16 17:42 UTC, Loori-R submitted a review, later dismissed

2024-12-17 08:51 UTC, hagen1778 requested changes
Thanks! The change doesn't address the following requirement:
> The change and mitigation procedure should be outlined in update notes.

from https://github.com/VictoriaMetrics/victorialogs-datasource/issues/156

2024-12-17 10:47 UTC, AndrewChubatiuk approved these changes

2024-12-17 11:55 UTC, Loori-R approved these changes

2024-12-17 11:55 UTC, Loori-R commented on CHANGELOG.md
> +field to `victoriametrics-logs-datasource`. After updating this field it needed to restart the Grafana server.**
What do you think about explicitly highlighting the Breaking Change? Here's the revised text:

⚠️ **Breaking Change: Plugin ID Updated**  

**Update Note 1:**  
In the new version of the plugin, the plugin ID has been updated. The new plugin ID is `victoriametrics-logs-datasource`. **This is a breaking change**: Grafana will treat this as a new plugin.  

- You must update the `allow_loading_unsigned_plugins` field in the `grafana.ini` or `defaults.ini` configuration file. **Example:**  
    ```ini  
    allow_loading_unsigned_plugins = victoriametrics-logs-datasource  
    ```

- If you are using provisioning, update the `type` field to `victoriametrics-logs-datasource` in your provisioning configuration.

- After making these changes, you must restart the Grafana server for the updates to take effect.  


```suggestion
⚠️ **Breaking Change: Plugin ID Updated**  

**Update Note 1:**  
In the new version of the plugin, the plugin ID has been updated. The new plugin ID is `victoriametrics-logs-datasource`. **This is a breaking change**: Grafana will treat this as a new plugin.  

- You must update the `allow_loading_unsigned_plugins` field in the `grafana.ini` or `defaults.ini` configuration file.  
    **Example:**  
    ```ini  
    allow_loading_unsigned_plugins = victoriametrics-logs-datasource  
    ```

- If you are using provisioning, update the `type` field to `victoriametrics-logs-datasource` in your provisioning configuration.

- After making these changes, you must restart the Grafana server for the updates to take effect.  
```

2024-12-17 12:19 UTC, Loori-R approved these changes

2024-12-17 16:06 UTC, merged